# Generated by Django 3.2.9 on 2021-11-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Actor name')),
                ('lastname', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('firstname',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Movie name')),
                ('description', models.TextField(default='movie def', null=True)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('watchCount', models.IntegerField(default=0, null=True)),
                ('rate', models.PositiveIntegerField(default=0, null=True)),
                ('productionDate', models.DateField(blank=True, null=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('modificationDate', models.DateField(auto_now=True)),
                ('actors', models.ManyToManyField(to='movies.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='my commentt:')),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie')),
            ],
        ),
    ]
