# Generated by Django 3.2.9 on 2021-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='modificationDate',
            new_name='mod_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='productionDate',
            new_name='prod_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='watchCount',
            new_name='watch_count',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default='Name...', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies'),
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default='Leave your review here'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='Description...', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
